### ISSUE TITLE
Support building for environments other than production

### ISSUE THREAD

**Issue by acorncom** [heroku/heroku-buildpack-ember-cli-deploy#3]
Currently we've got `ember deploy production` or `ember build --environment production` hard-coded here: https://github.com/heroku/heroku-buildpack-ember-cli-deploy/blob/master/buildpack/mrblib/buildpack/commands/compile.rb#L39-L43

I've got a client who primarily needs to be building production apps, but has some cases where we need the flexibility to build a staging app as well.  In the older tonycoco build pack they support an `EMBER_ENV` environment variable that allows that to be toggled (see https://github.com/tonycoco/heroku-buildpack-ember-cli#environment)

Any chance we'd be able to do something similar here?

**Comment by hone** [comment]
Yeah, that seems totally reasonable. Is `EMBER_ENV` something that ember uses or would this be a buildpack specific thing?

**Comment by fivetanley** [comment]
`EMBER_ENV` is something that ember uses

**Comment by hone** [comment]
@fivetanley if I don't set the flag, `--environment`, will ember build automatically pick it up? Can I just set `EMBER_ENV` to production if it isn't set?

**Comment by acorncom** [comment]
@hone You use it at the beginning of the command apparently (https://github.com/ember-cli/ember-cli/pull/753/files):

```
EMBER_ENV=staging ember build
```

**Comment by hone** [comment]
@acorncom awesome! If that's the case, I'm going to set `EMBER_ENV` to production if it isn't set already on the app.

**Comment by hone** [comment]
@acorncom @fivetanley could I get some eyes on PR #5?

**Comment by akatov** [comment]
@hone I already made a comment on PR #5 -  just wanted to repeat it here - ember-cli-deploy uses a "deploy target", which is a distinct concept from the Ember build environment (`EMBER_ENV`). The latter is passed as an argument to the function exported in `config/environment.js`, whereas the former is passed as an argument to the function exported in `config/deploy.js` in an ember-cli application that uses ember-cli-deploy.
In particular it is possible to run something like `EMBER_ENV=production ember deploy staging1` or `EMBER_ENV=development ember deploy staging2` (in particular this wouldn't uglify the JS output) or even `EMBER_ENV=development ember deploy production` (where the production deploy target is simply a name).
I'd prefer if I had a separate environment variable on Heroku I could configure the deploy target with (e.g. `EMBER_DEPLOY_TARGET`), or at least for the deploy target to always be something fixed in advance, e.g. as it is is now - this way I know that e.g. the `production` deploy target is the one that will always be used on heroku, but sometimes I would still want to use the `development` EMBER_ENV (e.g. if I don't want my assets uglified).

**Comment by Subtletree** [comment]
More support for having a separate `EMBER_DEPLOY_TARGET` variable.

I think a main use case is being able to deploy to production or staging which are identical except for certain config vars.

The reason for having a separate `EMBER_DEPLOY_TARGET` variable is that Ember doesn't have a concept of a `staging` environment and internally uses `EMBER_ENV === 'production'` to decide whether to uglify assets, what browser targets to deploy to etc.

So a staging env needs `EMBER_ENV = 'production'` to properly imitate the production environment and uses `deploy_target` to conditionally set other vars.

**Comment by joshwlewis** [comment]
This buildpack has been deprecated and won't be seeing any features or bugfixes in the future. You are welcome to fork the repo and implement the solution yourself if this is something you still need.
